#!/bin/bash
# ===========================
# LeakSight V1 — Generate Production .env File
# ===========================
# Source: docs/ARCHITECTURE.md (deployment section), infra setup guide Section 5
#
# Generates a .env file with cryptographically random secrets and documented
# defaults. Values that must be filled in manually are marked YOUR_VALUE_HERE.
#
# Usage: ./scripts/generate_env.sh [output_path]
#   Default output: .env in the current directory

set -euo pipefail

OUTPUT_FILE="${1:-.env}"

if [ -f "$OUTPUT_FILE" ]; then
    echo "ERROR: $OUTPUT_FILE already exists. Remove it first or specify a different path."
    exit 1
fi

# Generate cryptographically random secrets
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(64))")
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_hex(32))")

cat > "$OUTPUT_FILE" <<EOF
# ===========================
# LeakSight V1 — Production Environment Configuration
# ===========================
# Generated on: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Generated by: scripts/generate_env.sh
#
# IMPORTANT: This file contains secrets. Set permissions to 600:
#   chmod 600 $OUTPUT_FILE
#
# Values marked YOUR_VALUE_HERE must be filled in manually before deployment.

# ── Application ──
APP_ENV=production
SECRET_KEY=$SECRET_KEY
ALLOWED_HOSTS=YOUR_VALUE_HERE

# ── Database (PostgreSQL 15) ──
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=leaksight
POSTGRES_USER=leaksight_user
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# ── Redis ──
REDIS_URL=redis://redis:6379/0

# ── Celery ──
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1

# ── Document Storage ──
DOCUMENT_STORAGE_PATH=/app/data/documents
MAX_UPLOAD_SIZE_MB=200

# ── SMTP (Email Notifications) ──
SMTP_HOST=smtp-relay.brevo.com
SMTP_PORT=587
SMTP_USER=YOUR_VALUE_HERE
SMTP_PASSWORD=YOUR_VALUE_HERE
SMTP_FROM=YOUR_VALUE_HERE

# ── Tenant Defaults ──
DEFAULT_FUZZY_THRESHOLD=0.85
DEFAULT_DUPLICATE_WINDOW_DAYS=30
DEFAULT_MANUAL_REVIEW_THRESHOLD=0.70
DEFAULT_BASE_CURRENCY=INR
EOF

chmod 600 "$OUTPUT_FILE"

echo ""
echo "=========================================="
echo "  .env file generated: $OUTPUT_FILE"
echo "=========================================="
echo ""
echo "Random secrets generated:"
echo "  - SECRET_KEY (128 hex chars)"
echo "  - POSTGRES_PASSWORD (64 hex chars)"
echo ""
echo "You must manually set these values before deployment:"
echo "  - ALLOWED_HOSTS  (your domain, e.g., app.leaksight.com)"
echo "  - SMTP_USER      (Brevo login email)"
echo "  - SMTP_PASSWORD   (Brevo SMTP API key)"
echo "  - SMTP_FROM       (e.g., noreply@yourdomain.com)"
echo ""
echo "File permissions set to 600 (owner read/write only)."
echo "Confirm .env is in .gitignore before any push."
echo "=========================================="
